{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-app.serviceAccountName" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
  annotations:
    {{- include "sample-app.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false  # Security best practice - only mount if needed
{{- end }}